console.log(2>1)
console.log(2<1)
console.log(2==1)
console.log(2+2)
console.log("2"+1)
let a ="2"+1
console.log(typeof(a))
console.log(null>0)
console.log(null==0)
console.log(null<0)
console.log(undefined==0)
console.log(undefined>0)
console.log(undefined<0)
